# IMEC2001 Herramientas Computacionales 
## Clase 12 - Procesamiento de imágenes


## TABLA DE CONTENIDO

- 1.1. Cargar Librerías
- 1.2. Descargar y cargar imágenes
- 1.3. Contenido de una imágen
- 1.4. Visualización
- 1.6. Modificar canales
- 1.5. Redimensionamiento
- 1.6. Transformaciones afines
- 1.7. Detección de bordes
- 1.8. Dibujar sobre la imagen
- 1.9. Modificar y guardar imágenes

En esta clase se exploran varias técnicas y operaciones fundamentales con OpenCV que permitirán comenzar a trabajar en el procesamiento y análisis de imágenes.
Este cuaderno cubre la manipulación básica hasta conceptos más avanzados como detección de contornos y transformaciones morfológicas. 


## 1.1. Cargar Librerías

OpenCV es una biblioteca muy poderosa con muchas más funcionalidades. En este cuaderno vamos a experimentar con diferentes funciones que ayudan a comprender mejor cómo se constiuye una imagen en cuanto a su estructura de datos y la aplicón de herramientas para su manipulación.

In [1]:
!pip install pywget
!pip install opencv-python

  Obtaining dependency information for pywget from https://files.pythonhosted.org/packages/7f/95/50c18a5252cce92ed2b928e21fa9c5a56ee3c2c7504a86b04ab0314ee7e5/pywget-0.31-py2.py3-none-any.whl.metadata



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


  Obtaining dependency information for opencv-python from https://files.pythonhosted.org/packages/c7/ec/9dabb6a9abfdebb3c45b0cc52dec901caafef2b2c7e7d6a839ed86d81e91/opencv_python-4.9.0.80-cp37-abi3-win_amd64.whl.metadata
   ---------------------------------------- 0.0/38.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.6 MB 660.6 kB/s eta 0:00:59
   ---------------------------------------- 0.0/38.6 MB 495.5 kB/s eta 0:01:18
   ---------------------------------------- 0.0/38.6 MB 495.5 kB/s eta 0:01:18
   ---------------------------------------- 0.1/38.6 MB 328.6 kB/s eta 0:01:58
   ---------------------------------------- 0.1/38.6 MB 437.6 kB/s eta 0:01:29
   ---------------------------------------- 0.1/38.6 MB 502.3 kB/s eta 0:01:17
   ---------------------------------------- 0.1/38.6 MB 502.3 kB/s eta 0:01:17
   ---------------------------------------- 0.2/38.6 MB 476.3 kB/s eta 0:01:21
   ----


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
from pywget import wget
import cv2
import glob
import numpy as np

## 1.2. Descargar y cargar imágenes

Se pueden descargar imágenes directamente desde la web a través de su URL. 
En esta celda tenemos una lista de links a imágenes y se utiliza el paquete pywget para descargarlas.
También se utiliza el paquete glob para poder revisar los archivos jpg en el directorio de trabajo.

In [3]:
img_url=list()
img_url.append('https://i.pinimg.com/originals/5b/a1/98/5ba198c583f798939869ca854017ce4d.jpg')
img_url.append('https://khpet.com/cdn/shop/articles/when-do-puppies-start-walking_800x800.jpg?v=1593020034')
img_url.append('https://i.pinimg.com/736x/a2/41/bf/a241bf580bd666a05de1fa3b53f973e7.jpg')

#Descargemos algunas imágenes desde la web
if not glob.glob('./*.jpg'):
    for url in img_url:
        file=wget.download(url)        
img=[]
for file in glob.glob('./*.jpg'):
    img.append(cv2.imread(file))
    
#img contiene una lista de imagenes (pixeles)

    

100% [..............................................................................] 90656 / 90656

## 1.3. Contenido de una imágen

Una imagen digital se representa comúnmente como una matriz tridimensional de valores numéricos. Estos valores representan los píxeles que conforman la imagen. La forma en que estos píxeles están organizados y el significado detrás de sus valores depende del espacio de color utilizado por la imagen.

Los pixeles son la unidad básica programable con información visual en una pantalla digital o en este caso, dentro de una matriz que constituye una imagen digital. Cada pixel contiene datos sobre el brillo y posiblemente también sobre el color que debe representarse en ese punto específico de la imagen.

En OpenCV, el espacio de color predeterminado para las imágenes es BGR, lo cual significa Azul (Blue), Verde (Green) y Rojo (Red). Esto difiere del más conocido RGB porque simplemente invierte el orden de los canales rojo y azul.

Cada pixel en una imagen BGR está compuesto por tres componentes o canales:

- **B** (Azul): El primer canal representa la intensidad del color azul.
- **G** (Verde): El segundo canal representa la intensidad del color verde.
- **R** (Rojo): El tercer canal representa la intensidad del color rojo.

Por ejemplo, un pixel específico en una imagen podría tener un valor expresado como `[255, 0, 0]`. En formato BGR esto significaría que dicho pixel es completamente azul (`255` para azul), sin ninguna contribución verde (`0` para verde) ni roja (`0` para rojo).



In [4]:
#Miremos una de las imagenes para entender su contenido
idx=2
print('Shape:{}'.format(img[idx].shape))
# Los dos primeros indices representan el pixel i,j 
# el último indice representa el canal (BGR)
print(img[idx])

Shape:(570, 800, 3)
[[[ 51  50  40]
  [ 51  50  40]
  [ 50  50  38]
  ...
  [ 36  44  33]
  [ 35  44  34]
  [ 35  44  34]]

 [[ 51  50  40]
  [ 51  50  40]
  [ 50  50  38]
  ...
  [ 36  44  33]
  [ 35  44  34]
  [ 35  44  34]]

 [[ 52  50  39]
  [ 51  49  38]
  [ 50  48  37]
  ...
  [ 36  44  33]
  [ 35  44  34]
  [ 35  44  34]]

 ...

 [[143 179 185]
  [143 181 186]
  [144 182 187]
  ...
  [156 195 174]
  [149 195 172]
  [143 194 167]]

 [[142 180 184]
  [136 176 181]
  [136 175 183]
  ...
  [153 194 167]
  [147 192 165]
  [142 190 161]]

 [[142 180 184]
  [136 176 181]
  [136 175 183]
  ...
  [153 194 167]
  [147 192 165]
  [142 190 161]]]


## 1.4. Visualización
La visualización de una matriz de imagen se puede hacer con el comando `cv2.imshow`

Siempre que se abran las ventanas de imshow se deben cerrar usando `cv.destroyAllWindows()` para no bloquear el proceso del kernel.

Entonces utilizamos el comando `waitKey()` para esperar una entrada cualquiera del usuario antes de cerrar la ventana.

In [ ]:
#Visualizemos la imagen
cv2.imshow('Imagen', img[idx])
cv2.waitKey(0) # Espera hasta que se presione alguna tecla para continuar
cv2.destroyAllWindows() # Cierra todas las ventanas abiertas por OpenCV

def view(img):
    cv2.imshow("Imagen Redimensionada", img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

## 1.6. Modificar canales

Siendo la imagen una matriz (W,H,channels) podemos utilizar cualquier modificación sobre los valores numéricos de la matriz para manipular la imagen. 

Por ejemplo podríamos modificar todo un canal por completo y alterar los contenidos de color.

In [ ]:
# Como vimos previamente, la imagen contiene 3 canales.
# miremos que pasa si 'apagamos' dos de ellos
img_modificada=np.copy(img[idx])
img_modificada[:,:,0]=0
img_modificada[:,:,1]=0
view(img_modificada)

In [23]:
#Podemos combinar y sacar el promedio de BGR
img_modificada=np.copy(img[idx])
promedio=np.mean(img_modificada,2)
img_modificada[:,:,0]=promedio
img_modificada[:,:,1]=promedio
img_modificada[:,:,2]=promedio
view(img_modificada)

In [24]:
#Este proceso es equivalente a usar la transformación COLOR_BGR2GRAY
gris = cv2.cvtColor(img[idx], cv2.COLOR_BGR2GRAY)
view(gris)

## 1.5. Redimensionamiento

Para cambiar el tamaño de una imagen utilizando OpenCV. Primero, se define `nuevo_tamano` como una tupla que especifica las nuevas dimensiones deseadas para la imagen, en este caso, 1200 píxeles de ancho por 600 píxeles de alto. Luego, se utiliza la función `cv2.resize()` para redimensionar efectivamente la imagen 
Este procedimiento es útil cuando necesitamos ajustar las dimensiones de nuestras imágenes para diferentes aplicaciones.

In [21]:
nuevo_tamano = (1200, 600) # Ancho x Alto en pixeles
imagen_redimensionada = cv2.resize(img[idx], nuevo_tamano)
# Verificar el cambio mostrándola 
view(imagen_redimensionada)

## 1.6. Transformaciones afines

Una transformación afín es un tipo de operación en el procesamiento de imágenes y gráficos por computadora que altera la geometría de la imagen. Incluye rotaciones, traslaciones (movimientos), escalado (cambio de tamaño) y cizallamiento. Lo interesante de las transformaciones afines es que preservan puntos, rectas y planos. Las paralelas en el objeto original seguirán siendo paralelas en el objeto transformado.



In [25]:
# Obtener dimensiones de la imagen
alto, ancho = img[idx].shape[:2]
# Calcular el centro de la imagen 
centro = (ancho // 2, alto // 2)

# Generar la matriz de rotación.
# Aquí, estamos rotando la imagen 45 grados alrededor del centro sin cambiar su escala.
matriz_rotacion = cv2.getRotationMatrix2D(centro, 45, 1.0)

# Realizar la rotación
imagen_rotada = cv2.warpAffine(img[idx], matriz_rotacion, (ancho, alto))

view(imagen_rotada)

In [26]:
# Definir la matriz de traslación
M = np.float32([[1, 0, 200], [0, 1, 50]]) # Moverá la imagen 200 pixeles a la derecha y 50 pixeles hacia abajo.

trasladada = cv2.warpAffine(img[idx], M, (ancho, alto))
view(trasladada)

## 1.8. Detección de bordes

La detección de bordes es una técnica fundamental en el procesamiento de imágenes y la visión por computadora que se enfoca en identificar los puntos dentro de una imagen donde ocurre un cambio brusco o discontinuidad en la intensidad (brillo) o color. Estos cambios abruptos suelen corresponder a los límites o contornos de objetos dentro de la escena, lo cual hace a la detección de bordes especialmente útil para comprender mejor la estructura básica y las características distintivas presentes en una imagen.

Los bordes son importantes porque marcan las fronteras entre diferentes regiones y objetos, permitiendo al sistema distinguir entre fondos y elementos destacados, así como entender mejor formas, tamaños y otras propiedades geométricas. En términos prácticos, detectar correctamente estos bordes facilita tareas posteriores como el seguimiento de objetos, reconocimiento facial, segmentación semántica e incluso operaciones más avanzadas como reconstrucciones 3D a partir de múltiples imágenes.

In [27]:
# Los bordes de una imagen se relacionan con los pixeles donde el gradiente es alto.
gris = cv2.cvtColor(img[idx], cv2.COLOR_BGR2GRAY)
gradiente_x,gradiente_y=np.gradient(gris) #Calculamos el gradiente en x e y
mag_gradiente=np.sqrt(gradiente_x**2+gradiente_y**2)
view(mag_gradiente/np.max(mag_gradiente)) #Graficamos normalizando con la magnitud máxima
# OpenCV soporta floats, en cuyo caso los pixeles admiten valores entre 0 y 1.0

In [28]:
# Existe un método que utiliza tanto la magnitud como la dirección del gradiente para obtener los bordes
# Este método entrega una matriz binaria (1|0 clasificando pixeles si es o no borde)
bordes_canny = cv2.Canny(img[idx],100 ,150) 
view(bordes_canny)

## 1.9. Dibujar sobre la imagen

In [29]:
imagen_con_rectangulo = cv2.rectangle(np.copy(img[idx]), (centro[0]-50, centro[1]-50), (centro[0]+50, centro[1]+50), (255,0 ,0), thickness=3)
view(imagen_con_rectangulo)

## 1.10. Modificar y guardar imágenes

In [30]:
# Apliquemos varias manipulaciones sobre la imagen y guardemos el resultado en un nuevo archivo
gris = cv2.cvtColor(img[idx], cv2.COLOR_BGR2GRAY)
gradiente_x,gradiente_y=np.gradient(gris) #Calculamos el gradiente en x e y
mag_gradiente=np.sqrt(gradiente_x**2+gradiente_y**2)
mag_gradiente_normalizado=mag_gradiente/np.max(mag_gradiente)

c=1-mag_gradiente_normalizado
c=c[:,:,np.newaxis]
c=np.tile(c,(1,1,3))

imagen_modificada=(img[idx]*c).astype(np.uint8)
view(imagen_modificada)
cv2.imwrite('imagen_modificada.jpg', imagen_modificada)

#Compare las imagenes y explique la diferencia visual en relación al código

True